# Generated by Django 4.2.21 on 2026-05-09 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name="Ім'я")),
                ('last_name', models.CharField(max_length=50, verbose_name='Прізвище')),
                ('birth_date', models.DateField(verbose_name='Дата народження')),
                ('gender', models.CharField(choices=[('M', 'Чоловік'), ('F', 'Жінка')], max_length=1, verbose_name='Стать')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенти',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва предмета')),
                ('semester', models.PositiveSmallIntegerField(verbose_name='Семестр')),
                ('credits', models.PositiveSmallIntegerField(verbose_name='Кредити')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предмети',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата іспиту')),
                ('mark', models.PositiveSmallIntegerField(verbose_name='Оцінка')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='exams.student', verbose_name='Студент')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='exams.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Іспит',
                'verbose_name_plural': 'Іспити',
                'ordering': ['-date'],
            },
        ),
    ]
